// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/user/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenRequest) Reset() {
	*x = ValidateAccessTokenRequest{}
	mi := &file_module_user_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenRequest) ProtoMessage() {}

func (x *ValidateAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_module_user_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessTokenResponse) Reset() {
	*x = ValidateAccessTokenResponse{}
	mi := &file_module_user_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessTokenResponse) ProtoMessage() {}

func (x *ValidateAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_module_user_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAccessTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAccessTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ValidateAccessTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateAccessTokenResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ValidateAccessTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_module_user_auth_auth_proto protoreflect.FileDescriptor

const file_module_user_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1bmodule/user/auth/auth.proto\x12\tuser.auth\"?\n" +
	"\x1aValidateAccessTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x8a\x01\n" +
	"\x1bValidateAccessTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name2s\n" +
	"\vAuthService\x12d\n" +
	"\x13ValidateAccessToken\x12%.user.auth.ValidateAccessTokenRequest\x1a&.user.auth.ValidateAccessTokenResponseB&Z$go-grpc/proto/user-service/user;authb\x06proto3"

var (
	file_module_user_auth_auth_proto_rawDescOnce sync.Once
	file_module_user_auth_auth_proto_rawDescData []byte
)

func file_module_user_auth_auth_proto_rawDescGZIP() []byte {
	file_module_user_auth_auth_proto_rawDescOnce.Do(func() {
		file_module_user_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_user_auth_auth_proto_rawDesc), len(file_module_user_auth_auth_proto_rawDesc)))
	})
	return file_module_user_auth_auth_proto_rawDescData
}

var file_module_user_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_module_user_auth_auth_proto_goTypes = []any{
	(*ValidateAccessTokenRequest)(nil),  // 0: user.auth.ValidateAccessTokenRequest
	(*ValidateAccessTokenResponse)(nil), // 1: user.auth.ValidateAccessTokenResponse
}
var file_module_user_auth_auth_proto_depIdxs = []int32{
	0, // 0: user.auth.AuthService.ValidateAccessToken:input_type -> user.auth.ValidateAccessTokenRequest
	1, // 1: user.auth.AuthService.ValidateAccessToken:output_type -> user.auth.ValidateAccessTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_user_auth_auth_proto_init() }
func file_module_user_auth_auth_proto_init() {
	if File_module_user_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_user_auth_auth_proto_rawDesc), len(file_module_user_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_user_auth_auth_proto_goTypes,
		DependencyIndexes: file_module_user_auth_auth_proto_depIdxs,
		MessageInfos:      file_module_user_auth_auth_proto_msgTypes,
	}.Build()
	File_module_user_auth_auth_proto = out.File
	file_module_user_auth_auth_proto_goTypes = nil
	file_module_user_auth_auth_proto_depIdxs = nil
}
