// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/log/log/log.proto

package log

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogRequest) Reset() {
	*x = CreateLogRequest{}
	mi := &file_module_log_log_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogRequest) ProtoMessage() {}

func (x *CreateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_log_log_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogRequest.ProtoReflect.Descriptor instead.
func (*CreateLogRequest) Descriptor() ([]byte, []int) {
	return file_module_log_log_log_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLogRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *CreateLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateLogRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLogResponse) Reset() {
	*x = CreateLogResponse{}
	mi := &file_module_log_log_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogResponse) ProtoMessage() {}

func (x *CreateLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_log_log_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogResponse.ProtoReflect.Descriptor instead.
func (*CreateLogResponse) Descriptor() ([]byte, []int) {
	return file_module_log_log_log_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLogResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_module_log_log_log_proto protoreflect.FileDescriptor

const file_module_log_log_log_proto_rawDesc = "" +
	"\n" +
	"\x18module/log/log/log.proto\x12\alog.log\"\xe7\x01\n" +
	"\x10CreateLogRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.log.log.CreateLogRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x11CreateLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt2P\n" +
	"\n" +
	"LogService\x12B\n" +
	"\tCreateLog\x12\x19.log.log.CreateLogRequest\x1a\x1a.log.log.CreateLogResponseB@Z>github.com/anggardagasta/go-grpc/proto/syn-log-service/log;logb\x06proto3"

var (
	file_module_log_log_log_proto_rawDescOnce sync.Once
	file_module_log_log_log_proto_rawDescData []byte
)

func file_module_log_log_log_proto_rawDescGZIP() []byte {
	file_module_log_log_log_proto_rawDescOnce.Do(func() {
		file_module_log_log_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_log_log_log_proto_rawDesc), len(file_module_log_log_log_proto_rawDesc)))
	})
	return file_module_log_log_log_proto_rawDescData
}

var file_module_log_log_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_module_log_log_log_proto_goTypes = []any{
	(*CreateLogRequest)(nil),  // 0: log.log.CreateLogRequest
	(*CreateLogResponse)(nil), // 1: log.log.CreateLogResponse
	nil,                       // 2: log.log.CreateLogRequest.MetadataEntry
}
var file_module_log_log_log_proto_depIdxs = []int32{
	2, // 0: log.log.CreateLogRequest.metadata:type_name -> log.log.CreateLogRequest.MetadataEntry
	0, // 1: log.log.LogService.CreateLog:input_type -> log.log.CreateLogRequest
	1, // 2: log.log.LogService.CreateLog:output_type -> log.log.CreateLogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_module_log_log_log_proto_init() }
func file_module_log_log_log_proto_init() {
	if File_module_log_log_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_log_log_log_proto_rawDesc), len(file_module_log_log_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_log_log_log_proto_goTypes,
		DependencyIndexes: file_module_log_log_log_proto_depIdxs,
		MessageInfos:      file_module_log_log_log_proto_msgTypes,
	}.Build()
	File_module_log_log_log_proto = out.File
	file_module_log_log_log_proto_goTypes = nil
	file_module_log_log_log_proto_depIdxs = nil
}
