// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/user/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserRequest) Reset() {
	*x = FindUserRequest{}
	mi := &file_module_user_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserRequest) ProtoMessage() {}

func (x *FindUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserRequest.ProtoReflect.Descriptor instead.
func (*FindUserRequest) Descriptor() ([]byte, []int) {
	return file_module_user_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *FindUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserResponse) Reset() {
	*x = FindUserResponse{}
	mi := &file_module_user_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserResponse) ProtoMessage() {}

func (x *FindUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_user_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserResponse.ProtoReflect.Descriptor instead.
func (*FindUserResponse) Descriptor() ([]byte, []int) {
	return file_module_user_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *FindUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *FindUserResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *FindUserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_module_user_user_user_proto protoreflect.FileDescriptor

const file_module_user_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1bmodule/user/user/user.proto\x12\tuser.user\"*\n" +
	"\x0fFindUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x7f\n" +
	"\x10FindUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name2R\n" +
	"\vUserService\x12C\n" +
	"\bFindUser\x12\x1a.user.user.FindUserRequest\x1a\x1b.user.user.FindUserResponseBCZAgithub.com/anggardagasta/go-grpc/proto/syn-user-service/user;userb\x06proto3"

var (
	file_module_user_user_user_proto_rawDescOnce sync.Once
	file_module_user_user_user_proto_rawDescData []byte
)

func file_module_user_user_user_proto_rawDescGZIP() []byte {
	file_module_user_user_user_proto_rawDescOnce.Do(func() {
		file_module_user_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_user_user_user_proto_rawDesc), len(file_module_user_user_user_proto_rawDesc)))
	})
	return file_module_user_user_user_proto_rawDescData
}

var file_module_user_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_module_user_user_user_proto_goTypes = []any{
	(*FindUserRequest)(nil),  // 0: user.user.FindUserRequest
	(*FindUserResponse)(nil), // 1: user.user.FindUserResponse
}
var file_module_user_user_user_proto_depIdxs = []int32{
	0, // 0: user.user.UserService.FindUser:input_type -> user.user.FindUserRequest
	1, // 1: user.user.UserService.FindUser:output_type -> user.user.FindUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_user_user_user_proto_init() }
func file_module_user_user_user_proto_init() {
	if File_module_user_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_user_user_user_proto_rawDesc), len(file_module_user_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_user_user_user_proto_goTypes,
		DependencyIndexes: file_module_user_user_user_proto_depIdxs,
		MessageInfos:      file_module_user_user_user_proto_msgTypes,
	}.Build()
	File_module_user_user_user_proto = out.File
	file_module_user_user_user_proto_goTypes = nil
	file_module_user_user_user_proto_depIdxs = nil
}
