// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/book/book/book.proto

package book

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStockRequest) Reset() {
	*x = ValidateStockRequest{}
	mi := &file_module_book_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStockRequest) ProtoMessage() {}

func (x *ValidateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_book_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStockRequest.ProtoReflect.Descriptor instead.
func (*ValidateStockRequest) Descriptor() ([]byte, []int) {
	return file_module_book_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateStockRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type ValidateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateStockResponse) Reset() {
	*x = ValidateStockResponse{}
	mi := &file_module_book_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateStockResponse) ProtoMessage() {}

func (x *ValidateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_book_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateStockResponse.ProtoReflect.Descriptor instead.
func (*ValidateStockResponse) Descriptor() ([]byte, []int) {
	return file_module_book_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateStockResponse) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

type IncreaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockRequest) Reset() {
	*x = IncreaseStockRequest{}
	mi := &file_module_book_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockRequest) ProtoMessage() {}

func (x *IncreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_book_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockRequest.ProtoReflect.Descriptor instead.
func (*IncreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_module_book_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *IncreaseStockRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type IncreaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseStockResponse) Reset() {
	*x = IncreaseStockResponse{}
	mi := &file_module_book_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseStockResponse) ProtoMessage() {}

func (x *IncreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_book_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseStockResponse.ProtoReflect.Descriptor instead.
func (*IncreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_module_book_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *IncreaseStockResponse) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

type DecreaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockRequest) Reset() {
	*x = DecreaseStockRequest{}
	mi := &file_module_book_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockRequest) ProtoMessage() {}

func (x *DecreaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_book_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockRequest.ProtoReflect.Descriptor instead.
func (*DecreaseStockRequest) Descriptor() ([]byte, []int) {
	return file_module_book_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *DecreaseStockRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type DecreaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         string                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecreaseStockResponse) Reset() {
	*x = DecreaseStockResponse{}
	mi := &file_module_book_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecreaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecreaseStockResponse) ProtoMessage() {}

func (x *DecreaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_book_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecreaseStockResponse.ProtoReflect.Descriptor instead.
func (*DecreaseStockResponse) Descriptor() ([]byte, []int) {
	return file_module_book_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *DecreaseStockResponse) GetStock() string {
	if x != nil {
		return x.Stock
	}
	return ""
}

var File_module_book_book_book_proto protoreflect.FileDescriptor

const file_module_book_book_book_proto_rawDesc = "" +
	"\n" +
	"\x1bmodule/book/book/book.proto\x12\tbook.book\"/\n" +
	"\x14ValidateStockRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"-\n" +
	"\x15ValidateStockResponse\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\tR\x05stock\"/\n" +
	"\x14IncreaseStockRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"-\n" +
	"\x15IncreaseStockResponse\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\tR\x05stock\"/\n" +
	"\x14DecreaseStockRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"-\n" +
	"\x15DecreaseStockResponse\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\tR\x05stock2\x89\x02\n" +
	"\vUserService\x12R\n" +
	"\rValidateStock\x12\x1f.book.book.ValidateStockRequest\x1a .book.book.ValidateStockResponse\x12R\n" +
	"\rIncreaseStock\x12\x1f.book.book.IncreaseStockRequest\x1a .book.book.IncreaseStockResponse\x12R\n" +
	"\rDecreaseStock\x12\x1f.book.book.DecreaseStockRequest\x1a .book.book.DecreaseStockResponseBCZAgithub.com/anggardagasta/go-grpc/proto/syn-book-service/book;bookb\x06proto3"

var (
	file_module_book_book_book_proto_rawDescOnce sync.Once
	file_module_book_book_book_proto_rawDescData []byte
)

func file_module_book_book_book_proto_rawDescGZIP() []byte {
	file_module_book_book_book_proto_rawDescOnce.Do(func() {
		file_module_book_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_book_book_book_proto_rawDesc), len(file_module_book_book_book_proto_rawDesc)))
	})
	return file_module_book_book_book_proto_rawDescData
}

var file_module_book_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_module_book_book_book_proto_goTypes = []any{
	(*ValidateStockRequest)(nil),  // 0: book.book.ValidateStockRequest
	(*ValidateStockResponse)(nil), // 1: book.book.ValidateStockResponse
	(*IncreaseStockRequest)(nil),  // 2: book.book.IncreaseStockRequest
	(*IncreaseStockResponse)(nil), // 3: book.book.IncreaseStockResponse
	(*DecreaseStockRequest)(nil),  // 4: book.book.DecreaseStockRequest
	(*DecreaseStockResponse)(nil), // 5: book.book.DecreaseStockResponse
}
var file_module_book_book_book_proto_depIdxs = []int32{
	0, // 0: book.book.UserService.ValidateStock:input_type -> book.book.ValidateStockRequest
	2, // 1: book.book.UserService.IncreaseStock:input_type -> book.book.IncreaseStockRequest
	4, // 2: book.book.UserService.DecreaseStock:input_type -> book.book.DecreaseStockRequest
	1, // 3: book.book.UserService.ValidateStock:output_type -> book.book.ValidateStockResponse
	3, // 4: book.book.UserService.IncreaseStock:output_type -> book.book.IncreaseStockResponse
	5, // 5: book.book.UserService.DecreaseStock:output_type -> book.book.DecreaseStockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_book_book_book_proto_init() }
func file_module_book_book_book_proto_init() {
	if File_module_book_book_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_book_book_book_proto_rawDesc), len(file_module_book_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_book_book_book_proto_goTypes,
		DependencyIndexes: file_module_book_book_book_proto_depIdxs,
		MessageInfos:      file_module_book_book_book_proto_msgTypes,
	}.Build()
	File_module_book_book_book_proto = out.File
	file_module_book_book_book_proto_goTypes = nil
	file_module_book_book_book_proto_depIdxs = nil
}
